Update check job

diff --git a/.github/workflows/bootstrap.yml b/.github/workflows/bootstrap.yml
--- a/.github/workflows/bootstrap.yml
+++ b/.github/workflows/bootstrap.yml
@@ -202,6 +202,18 @@ jobs:
           )
         uses: hmarr/debug-action@v2
 
+      - name: Dump steps context
+        id: dump_steps_context
+        if: >
+          failure() || (
+            success() &&
+            inputs.log_severity != 'ERROR'
+          )
+        env:
+          STEPS_CONTEXT: ${{ toJson(steps) }}
+        run: |
+          echo "${STEPS_CONTEXT}"
+
   plan:
     name: "🗓️ Plan"
     needs: check
