Change azure login script

diff --git a/.github/workflows/bootstrap.yml b/.github/workflows/bootstrap.yml
--- a/.github/workflows/bootstrap.yml
+++ b/.github/workflows/bootstrap.yml
@@ -315,42 +315,67 @@ jobs:
           persist-credentials: false
           fetch-depth: 1
 
-      - name: Check Client secret
-        id: client_secret
-        run: |
-          if [ '${{ secrets.AZURE_CLIENT_SECRET }}' = '' ]; then
-            echo 'Secret is not present, Log in to Azure with federated credentials.'
-            echo 'exist=false' >> "$GITHUB_OUTPUT"
-          else
-            echo 'Secret is present, Log in to Azure with secret.'
-            echo 'exist=true' >> "$GITHUB_OUTPUT"
-          fi
-
-      - name: Log in to Azure (Federated)
-        id: login_open_id
-        if: steps.client_secret.outputs.exist != 'true'
-        uses: azure/login@v1
-        with:
-          client-id: ${{ inputs.azure_client_id || secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ inputs.azure_tenant_id || secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ inputs.azure_subscription_id || secrets.AZURE_SUBSCRIPTION_ID  }}
-
-      - name: Log in to Azure (Secret)
-        id: login_secret
-        if: steps.client_secret.outputs.exist == 'true'
+      - name: Log in to Azure
+        id: azure_login
         env:
           CLIENT_ID: ${{ inputs.azure_client_id || secrets.AZURE_CLIENT_ID }}
           TENANT_ID: ${{ inputs.azure_tenant_id || secrets.AZURE_TENANT_ID }}
           SEVERITY: ${{ inputs.log_severity }}
         run: |
+          set -e
+          log="${LOG_PATH}/${GITHUB_ACTION}.log"
+          trap 'error $? $LINENO "$BASH_COMMAND" $log' ERR
+          error() {
+            msg="Error on or near line $(expr $2 + 1) (exit code $1)"
+            msg+=" occurred at $(date '+%Y-%m-%d %H:%M:%S'): $3"
+            echo "::error line=$(expr $2 + 1)::$msg"
+            echo "$msg" >> "$4"
+            log_output "$4"
+            exit $1
+          }
+          log_output() {
+            if test -f $1; then
+              result=$(
+                cat $1 | \
+                sed -r 's/^([[:space:]]+)([-+~x])[[:space:]]/\2\1/g' | \
+                sed -e 's/^~/!/g'
+              )
+              if test -n "${result}"; then
+                {
+                  echo 'result<<75cfa50190dc802c'
+                  echo -e '## Azure login\n'
+                  echo '```text'
+                  echo "${result}"
+                  echo -e '```\n'
+                  echo '75cfa50190dc802c'
+                } >> "$GITHUB_OUTPUT"
+              fi
+            fi
+          }
           case "${SEVERITY}" in
             ERROR)   log_severity=' --only-show-errors';;
             VERBOSE) log_severity=' --verbose';;
             DEBUG)   log_severity=' --debug';;
             *)       log_severity='';;
           esac
-          az login --service-principal -t ${TENANT_ID} -u ${CLIENT_ID} \
-            -p '${{ secrets.AZURE_CLIENT_SECRET }}' $log_severity
+          cmd="az login --service-principal -t ${TENANT_ID} -u ${CLIENT_ID}"
+          if test -n '${{ secrets.AZURE_CLIENT_SECRET }}'; then
+            cmd+=" -p ${{ secrets.AZURE_CLIENT_SECRET }}"
+          else
+            audience='api://AzureADTokenExchange'
+            url="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${audience}"
+            token=$(
+              curl -H \
+                "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
+                "${url}" | jq -r '.value'
+            )
+            echo "::add-mask::${token}"
+            cmd+=" --federated-token ${token}"
+          fi
+          cmd+=" --allow-no-subscriptions ${log_severity}"
+          echo "Run: ${cmd}" | tee -a $log
+          eval "${cmd}" 1> >(tee -a $log) 2> >(tee -a $log >&2)
+          log_output $log
 
       - name: Bicep install
         id: bicep_install
@@ -852,6 +877,7 @@ jobs:
         id: get_results
         if: always()
         env:
+          AZURE_LOGIN: ${{ steps.azure_login.outputs.result }}
           BICEP_INSTALL: ${{ steps.bicep_install.outputs.result }}
           BICEP_BUILD: ${{ steps.bicep_build.outputs.result }}
           BICEP_BUILD_PARAM: ${{ steps.bicep_build_params.outputs.result }}
@@ -867,6 +893,7 @@ jobs:
           esac
           all_results="${WHAT_IF}"
           all_results+=$(echo -e "\n\n${COST}")
+          all_results+=$(echo -e "\n\n${AZURE_LOGIN}")
           all_results+=$(echo -e "\n\n${BICEP_INSTALL}")
           all_results+=$(echo -e "\n\n${BICEP_BUILD}")
           all_results+=$(echo -e "\n\n${BICEP_BUILD_PARAM}")
